sudo: false
language: python
notifications:
  email: false
python:
  - 2.7
  - 2.6
  - 3.3
  - 3.4
  - 3.5
  - pypy
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install ordereddict; fi
  - pip install https://github.com/pyexcel/pyexcel-xls/archive/master.zip
  - touch requirements.txt
  - pip install -r tests/requirements.txt
script:
  make test
after_success:
  codecov