sudo: false
language: python
notifications:
  email: false
python:
  - pypy
  - 2.6
  - 2.7
  - pypy3
  - 3.3
  - 3.4
  - 3.5
before_install:
  - if [[ -f rnd_requirements.txt ]]; then
      pip install --upgrade "setuptools==17.1" ;
      pip install -r rnd_requirements.txt ;
    fi
  - pip install -r tests/requirements.txt
script:
  make test
after_success:
  codecov
